"""increase external_id length

Revision ID: 0a9baceeb93d
Revises: d49ad1dd2796
Create Date: 2026-06-21 13:15:29.649945
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0a9baceeb93d'
down_revision: str | None = 'd49ad1dd2796'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
